//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public Location()
        {
            this.EmployeeDatas = new HashSet<EmployeeData>();
        }
    
        public int LocationId { get; set; }
        public string Location1 { get; set; }
    
        public virtual ICollection<EmployeeData> EmployeeDatas { get; set; }
    }
}
